name: flutter_pickers
description: Flutter selector class library, including date and time selector (settable range), single selector (can be used for gender, occupation, education, constellation, etc.), city address selector (sub-provincial, prefecture and county level), Digital selector (can be used for age, height, weight, temperature, etc.), etc.... Welcome Fork & pr to contribute your code and learn together
description2: flutter 选择器类库，包括日期及时间选择器（可设置范围）、单项选择器（可用于性别、职业、学历、星座等）、城市地址选择器（分省级、地级及县级）、数字选择器（可用于年龄、身高、体重、温度等）等…… 欢迎Fork & pr贡献您的代码，大家共同学习
version: 0.0.2
homepage: https://github.com/longer96/flutter_pickers

environment:
  sdk: ">=1.19.0 <3.0.0"
  flutter: ">=0.4.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^4.0.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter: