name: flutter_pickers
description: Flutter selector library, including date and time selector, single item selector (gender, occupation, education, constellation), city address selector, etc.
#description2: flutter 选择器类库，包括日期及时间选择器（可设置范围）、单项选择器（可用于性别、职业、学历、星座等）、城市地址选择器（分省级、地级及县级）、数字选择器（可用于年龄、身高、体重、温度等）等…… 欢迎Fork & pr贡献您的代码，大家共同学习
version: 2.1.9
homepage: https://github.com/longer96/flutter_pickers

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=0.4.1'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
